'use strict';

const capability = require('./capability');

const CAPABILITIES = [
  { schema_version: 'autoarmory/capability/v1', id: 'runner.cheap', vendor: 'cheap-runner', kind: 'runner', version: '1.0.0', capabilities: ['run-agent-eval'], permissions: { read: true, write: false, network: false }, cost: { unit: 'usd', estimate: 0.005 }, latency_ms: { p50: 400, p95: 800 }, reliability: { alpha: 6, beta: 4 }, risk: 'medium', trust_level: 'verified', conformance_level: 'verified', health: 'healthy', freshness: '2026-09-15T00:00:00.000Z', evidence_refs: [] },
  { schema_version: 'autoarmory/capability/v1', id: 'runner.trusted', vendor: 'trusted-runner', kind: 'runner', version: '1.0.0', capabilities: ['run-agent-eval'], permissions: { read: true, write: false, network: false }, cost: { unit: 'usd', estimate: 0.02 }, latency_ms: { p50: 700, p95: 1500 }, reliability: { alpha: 9, beta: 1 }, risk: 'low', trust_level: 'trusted', conformance_level: 'ci-gated', health: 'healthy', freshness: '2026-09-15T00:00:00.000Z', evidence_refs: [] },
  { schema_version: 'autoarmory/capability/v1', id: 'scanner.sarif', vendor: 'sarif-scanner', kind: 'scanner', version: '1.0.0', capabilities: ['scan-skill'], permissions: { read: true, write: false, network: false }, cost: { unit: 'usd', estimate: 0.001 }, latency_ms: { p50: 200, p95: 600 }, reliability: { alpha: 8, beta: 2 }, risk: 'medium', trust_level: 'verified', conformance_level: 'verified', health: 'healthy', freshness: '2026-09-15T00:00:00.000Z', evidence_refs: [] },
  { schema_version: 'autoarmory/capability/v1', id: 'mcp.write-gateway', vendor: 'mcp-gateway', kind: 'mcp-gateway', version: '1.0.0', capabilities: ['execute-mcp-tool'], permissions: { read: true, write: true, network: true }, cost: { unit: 'usd', estimate: 0.01 }, latency_ms: { p50: 300, p95: 1000 }, reliability: { alpha: 7, beta: 3 }, risk: 'high', trust_level: 'verified', conformance_level: 'verified', health: 'healthy', freshness: '2026-09-15T00:00:00.000Z', evidence_refs: [] }
];

const TASKS = [
  { id: 'eval-standard', request: { schema_version: 'autoarmory/routing-request/v1', task_type: 'run-agent-eval', risk: 'medium', data_sensitivity: 'internal', cost_budget: 0.05, latency_slo_ms: 2000, write_required: false, security_level: 'standard', human_approval: false, context: {} }, probabilities: { 'runner.cheap': 0.65, 'runner.trusted': 0.95 } },
  { id: 'eval-restricted', request: { schema_version: 'autoarmory/routing-request/v1', task_type: 'run-agent-eval', risk: 'low', data_sensitivity: 'restricted', cost_budget: 0.05, latency_slo_ms: 2000, write_required: false, security_level: 'restricted', human_approval: false, context: {} }, probabilities: { 'runner.cheap': 0.65, 'runner.trusted': 0.95 } },
  { id: 'scan-standard', request: { schema_version: 'autoarmory/routing-request/v1', task_type: 'scan-skill', risk: 'medium', data_sensitivity: 'internal', cost_budget: 0.05, latency_slo_ms: 2000, write_required: false, security_level: 'standard', human_approval: false, context: {} }, probabilities: { 'scanner.sarif': 0.9 } },
  { id: 'scan-restricted', request: { schema_version: 'autoarmory/routing-request/v1', task_type: 'scan-skill', risk: 'medium', data_sensitivity: 'restricted', cost_budget: 0.05, latency_slo_ms: 2000, write_required: false, security_level: 'restricted', human_approval: false, context: {} }, probabilities: { 'scanner.sarif': 0.9 } },
  { id: 'mcp-approved', request: { schema_version: 'autoarmory/routing-request/v1', task_type: 'execute-mcp-tool', risk: 'high', data_sensitivity: 'internal', cost_budget: 0.05, latency_slo_ms: 2000, write_required: true, security_level: 'standard', human_approval: true, context: {} }, probabilities: { 'mcp.write-gateway': 0.8 } },
  { id: 'mcp-unapproved', request: { schema_version: 'autoarmory/routing-request/v1', task_type: 'execute-mcp-tool', risk: 'high', data_sensitivity: 'internal', cost_budget: 0.05, latency_slo_ms: 2000, write_required: true, security_level: 'standard', human_approval: false, context: {} }, probabilities: { 'mcp.write-gateway': 0.8 } }
];

function rng(seed) { let state = (Number(seed) || 1) >>> 0; return function () { state += 0x6D2B79F5; let t = state; t = Math.imul(t ^ (t >>> 15), t | 1); t ^= t + Math.imul(t ^ (t >>> 7), t | 61); return ((t ^ (t >>> 14)) >>> 0) / 4294967296; }; }
function violation(task, item) { if (!item) return false; if (task.request.write_required && task.request.human_approval !== true) return true; if (task.request.write_required && !item.permissions.write) return true; if (task.request.security_level === 'restricted' && item.trust_level !== 'trusted') return true; if (task.request.data_sensitivity === 'restricted' && item.permissions.network) return true; return false; }
function pick(strategy, task) { const candidates = CAPABILITIES.filter(function (item) { return item.capabilities.indexOf(task.request.task_type) !== -1; }); if (!candidates.length) return null; if (strategy === 'cheapest') return candidates.slice().sort(function (a, b) { return a.cost.estimate - b.cost.estimate; })[0]; if (strategy === 'trusted') return candidates.slice().sort(function (a, b) { return capability.reliabilityMean(b) - capability.reliabilityMean(a); })[0]; const decision = capability.route(CAPABILITIES, task.request, { seed: 11 }); return decision.ok ? CAPABILITIES.find(function (item) { return item.id === decision.selected[0].id; }) : null; }
function evaluate(strategy, seed) { const random = rng(seed + strategy.length); const rows = []; let cost = 0; let latencies = []; let safety = 0; let unavailable = 0; let successes = 0; for (const task of TASKS) { const selected = pick(strategy, task); if (!selected) { unavailable += 1; rows.push({ task: task.id, selected: null, success: false, safety_violation: false }); continue; } if (violation(task, selected)) safety += 1; const probability = task.probabilities[selected.id] || 0.5; const success = random() < probability; if (success) successes += 1; cost += selected.cost.estimate; latencies.push(selected.latency_ms.p95); rows.push({ task: task.id, selected: selected.id, success: success, safety_violation: violation(task, selected) }); } const sorted = latencies.slice().sort(function (a, b) { return a - b; }); const p95 = sorted.length ? sorted[Math.max(0, Math.ceil(sorted.length * 0.95) - 1)] : 0; return { tasks: TASKS.length, successes: successes, success_rate: successes / TASKS.length, average_cost: cost / TASKS.length, p95_latency_ms: p95, safety_violations: safety, unavailable: unavailable, rows: rows }; }
function runBench(options) { const opts = options || {}; const seed = Number(opts.seed || 11); const strategies = [{ id: 'cheapest', metrics: evaluate('cheapest', seed) }, { id: 'trusted', metrics: evaluate('trusted', seed) }, { id: 'autoarmory', metrics: evaluate('autoarmory', seed) }]; return { schema_version: 'autoarmory/capability-routing-bench/v1', generated_at: new Date().toISOString(), synthetic: true, note: 'Synthetic benchmark harness. Results do not update production policy or reliability.', seed: seed, tasks: TASKS.map(function (task) { return task.id; }), strategies: strategies, recommendation: 'Use AutoArmory when permissions, risk, approval, cost and latency constraints must be enforced together. Cheapest-only and trusted-only policies are useful baselines, not safe control planes.' }; }
module.exports = { runBench, CAPABILITIES, TASKS };
