'use strict';
const fs=require('fs');
const os=require('os');
const path=require('path');
const {spawnSync}=require('child_process');
function must(c,m){if(!c)throw new Error(m);}
const repo=path.resolve(__dirname,'..');
const script=path.join(repo,'scripts','history-runner.js');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'autoarmory-history-runner-'));
const state=path.join(temp,'state');
const pending=path.join(state,'pending');
fs.mkdirSync(pending,{recursive:true});
fs.writeFileSync(path.join(pending,'change-win-service.json'),JSON.stringify({schema_version:'autoarmory/pending-change/v1',change_id:'change-win-service',session_id:'s1',turn_id:'t1',source_message_id:'m1',changed_files:[],commands:[],check_status:'check_gap',signals:['risk_signal','check_gap'],verifier_id:'windows-service-state',expected_transition:'STATE->RUNNING'}),'utf8');
let r=spawnSync(process.execPath,[script,'--drain','--state',state,'--repo',repo,'--json'],{encoding:'utf8'});
must(r.status===0,'history runner must succeed: '+r.stderr+r.stdout);
const report=JSON.parse(r.stdout);
must(report.history_derived_run_count===1 && report.unverifiable_count===0 && report.failed_count===0,'history runner must close one real verifier run');
const reuseFile=path.join(state,'reuse-records','change-win-service.json');
const reuse=JSON.parse(fs.readFileSync(reuseFile,'utf8'));
must(reuse.status==='closed' && reuse.verifier==='windows-service-state' && reuse.run.result==='pass','reuse record must bind the real verifier result');
must(fs.readdirSync(pending).length===0,'pending job must be drained');
const before=fs.readFileSync(reuseFile,'utf8');
r=spawnSync(process.execPath,[script,'--drain','--state',state,'--repo',repo,'--json'],{encoding:'utf8'});
must(r.status===0,'second drain must succeed');
must(JSON.parse(r.stdout).history_derived_run_count===0,'second drain must be idempotent');
must(fs.readFileSync(reuseFile,'utf8')===before,'reuse record must not change on rerun');
fs.writeFileSync(path.join(pending,'change-no-verifier.json'),JSON.stringify({schema_version:'autoarmory/pending-change/v1',change_id:'change-no-verifier',session_id:'s2',signals:['risk_signal'],verifier_id:null}),'utf8');
r=spawnSync(process.execPath,[script,'--drain','--state',state,'--repo',repo,'--json'],{encoding:'utf8'});
must(r.status===0 && JSON.parse(r.stdout).unverifiable_count===1,'missing verifier must become unverifiable');
const unv=JSON.parse(fs.readFileSync(path.join(state,'reuse-records','change-no-verifier.json'),'utf8'));
must(unv.status==='unverifiable','unverifiable reuse record must not close');
fs.writeFileSync(path.join(pending,'change-project-test.json'),JSON.stringify({schema_version:'autoarmory/pending-change/v1',change_id:'change-project-test',session_id:'s3',signals:['check_gap'],verifier_candidate:{kind:'project_test',ref:'node tests/signal-recall.js'},commands:['node tests/signal-recall.js']}),'utf8');
r=spawnSync(process.execPath,[script,'--drain','--state',state,'--repo',repo,'--json'],{encoding:'utf8'});
must(r.status===0,'project test drain must succeed');
const projectReuse=JSON.parse(fs.readFileSync(path.join(state,'reuse-records','change-project-test.json'),'utf8'));
must(projectReuse.status==='closed' && projectReuse.run.exit_code===0,'whitelisted project test must close');
fs.writeFileSync(path.join(pending,'change-non-whitelist.json'),JSON.stringify({schema_version:'autoarmory/pending-change/v1',change_id:'change-non-whitelist',session_id:'s4',signals:['risk_signal'],verifier_candidate:{kind:'project_test',ref:'rm -rf production'},commands:['rm -rf production']}),'utf8');
r=spawnSync(process.execPath,[script,'--drain','--state',state,'--repo',repo,'--json'],{encoding:'utf8'});
must(r.status===0 && JSON.parse(r.stdout).unverifiable_count===1,'non-whitelisted command must be unverifiable');
fs.writeFileSync(path.join(pending,'change-missing-file.json'),JSON.stringify({schema_version:'autoarmory/pending-change/v1',change_id:'change-missing-file',session_id:'s5',signals:['file_changed'],verifier_candidate:{kind:'file_hash',ref:'missing-file.txt'}}),'utf8');
r=spawnSync(process.execPath,[script,'--drain','--state',state,'--repo',repo,'--json'],{encoding:'utf8'});
must(r.status===0 && JSON.parse(r.stdout).unverifiable_count===1,'missing file hash target must be unverifiable');
console.log('history runner tests passed: pending -> real run -> close -> reuse, idempotent, unverifiable stays open');