'use strict';
const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');
const { classifyFinding, triage } = require('../src/lib/triage');
function must(condition, message) { if (!condition) throw new Error(message); }
const evidence = [{ id: 'ev-1' }];
const rawMustFix = { id: 'red-1', kind: 'safety_boundary', source_decision_id: 'route-1', evidence_refs: evidence };
const rawBacklog = { id: 'backlog-1', kind: 'missing_consumer', source_decision_id: 'case-1', evidence_refs: evidence };
const rawTheoretical = { id: 'theory-1', kind: 'theoretical_completeness', source_decision_id: 'case-3', evidence_refs: evidence };
const mustFix = classifyFinding(rawMustFix);
must(mustFix.category === 'must_fix_now', 'external/safety red must be must_fix_now');
const liveConflict = classifyFinding({ id: 'conflict-1', kind: 'live_fact_conflict', source_decision_id: 'run-1', evidence_refs: evidence });
must(liveConflict.category === 'must_fix_now', 'live fact conflict must be must_fix_now');
const backlog = classifyFinding({ id: 'backlog-1', kind: 'missing_stop_condition', source_decision_id: 'case-1', evidence_refs: evidence, missing: ['stop_condition'] });
must(backlog.category === 'backlog', 'missing stop condition must go to backlog');
const lowImpact = classifyFinding({ id: 'docs-1', kind: 'documentation', source_decision_id: 'case-2', evidence_refs: evidence, decision_impact: false });
must(lowImpact.category === 'only_if_decision_impact', 'docs without a decision impact must not be must-fix');
const theoretical = classifyFinding({ id: 'theory-1', kind: 'theoretical_completeness', source_decision_id: 'case-3', evidence_refs: evidence });
must(theoretical.category === 'do_not_do', 'theoretical completeness must be do_not_do');
const noEvidence = classifyFinding({ id: 'red-no-evidence', kind: 'safety_boundary', source_decision_id: 'route-2', evidence_refs: [] });
must(noEvidence.category === 'needs_evidence', 'hard red without evidence must fail closed as needs_evidence');
const report = triage([{ id: 'red-1', kind: 'safety_boundary', source_decision_id: 'route-1', evidence_refs: evidence }, { id: 'backlog-1', kind: 'missing_consumer', source_decision_id: 'case-1', evidence_refs: evidence }, { id: 'theory-1', kind: 'theoretical_completeness', source_decision_id: 'case-3', evidence_refs: evidence }]);
must(report.counts.must_fix_now === 1 && report.counts.backlog === 1 && report.counts.do_not_do === 1 && report.blocking_count === 1, 'triage counts must separate now, backlog and never-do');
const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'autoarmory-triage-'));
const input = path.join(temp, 'findings.jsonl');
fs.writeFileSync(input, [rawMustFix, rawBacklog, rawTheoretical].map(function (item) { return JSON.stringify(item); }).join('\n') + '\n', 'utf8');
const script = path.resolve(__dirname, '..', 'scripts', 'triage.js');
const blocked = spawnSync(process.execPath, [script, '--input', input, '--json', '--enforce'], { encoding: 'utf8' });
must(blocked.status === 1 && /"must_fix_now"/.test(blocked.stdout), 'triage enforce must block while must-fix remains: ' + blocked.stdout + blocked.stderr);
fs.writeFileSync(input, [rawBacklog, rawTheoretical].map(function (item) { return JSON.stringify(item); }).join('\n') + '\n', 'utf8');
const allowed = spawnSync(process.execPath, [script, '--input', input, '--json', '--enforce'], { encoding: 'utf8' });
must(allowed.status === 0, 'backlog and do-not-do must not block the current action: ' + allowed.stdout + allowed.stderr);
console.log('triage tests passed: must_fix_now, live conflict, backlog, only_if_decision_impact, do_not_do, needs_evidence, enforce semantics');